baseurl = "https://jasik.xyz"
languageCode = "en"
title = "Bowl of TARDIS"

copyright = "&copy; Caleb Jasik 2018-2020"

MetaDataFormat = "toml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

enableRobotsTXT = true

enableGitInfo = true

pygmentsUseClasses = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
description = "Bowl of TARDIS is the space for Caleb Jasik on the web. Mostly random blog posts, and occasional pictures"


[author]
  name = "Caleb Jasik"
  homepage = "https://jasik.xyz"
  email = "calebjasik@jasik.xyz"

[markup.highlight]
  style = "dracula"

[imaging]
  quality = 75

[markup.goldmark.renderer]
  unsafe = true

  [privacy]
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    simple = true
  [privacy.vimeo]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true
