baseURL = "https://caleb-jasik-blog.netlify.com"
languageCode = "en-us"
title = "Bowl of TARDIS"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# set this if it screws things up to not have set. Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# Paginate = 7
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "my little attempt at a blog"
  facebook = ""
  twitter_username = "calebjasik"
  instagram_username = "calebjasik"
  youtube_username = "calebjasik"
  github_username = "jasikpark"
  # linkedin = "https://linkedin.com/in/calebjasik"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/uploads/see_the_trees.jpg"
  recent_posts_number = 2

[params.highlight]
  style = "zenburn"

pygmentsCodeFences = true
