[build]
publish = "public/"
command = "export PERCY_BRANCH=\"$BRANCH\";export PERCY_PULL_REQUEST=\"$REVIEW_ID\";hugo --minify && percy snapshot public/"

[context.production.environment]
HUGO_VERSION = "0.58.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "export PERCY_BRANCH=\"$BRANCH\";export PERCY_PULL_REQUEST=\"$REVIEW_ID\";hugo -b $DEPLOY_PRIME_URL --minify && percy snapshot public/"

[context.split1.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "export PERCY_BRANCH=\"$BRANCH\";export PERCY_PULL_REQUEST=\"$REVIEW_ID\";hugo --buildFuture -b $DEPLOY_PRIME_URL --minify && percy snapshot public/"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.0"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
