[build]
command = "hugo --gc"
publish = "public/"

[build.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.68.3"
RUBY_VERSION = "2.6.2"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"