[build]
publish = "public/"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.55.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "PERCY_BRANCH=\"$BRANCH\";PERCY_PULL_REQUEST=\"$PULL_REQUEST\";hugo --buildFuture -b $DEPLOY_PRIME_URL && percy snapshot public/"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.3"

[context.branch-deploy]
command = "hugo"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
