name: Check Markdown links

on:
  schedule:
    # runs daily at 3am
    - cron: '0 3 * * *'
  push:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.4.0