name: Link Check

on:
  schedule:
    # runs daily at 3am
    - cron: '0 3 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: peaceiris/actions-hugo-link-check@v0.56.3
      env:
        HUGO_OPTIONS : --buildDrafts
        OPTIONS: "-e 'http://localhost:8000'"