name: Percy
on:
  push:
    branches:
      - "master"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          image: latest-ext
          command: "-b 'https://jasik.xyz'"
          env: "production"
      - name: Percy
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "public"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
